server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.66.11
    port: 5672
    username: leellun
    password: 123456
    virtual-host: /