mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/ds_0?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: leellun
        password: liulun666
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/ds_1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: leellun
        password: liulun666
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds${id % 2}
      broadcast-tables: t_udict
      binding-tables: t_user
      tables:
        t_user:
          actual-data-nodes: ds${0..1}.t_user${0..1}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds${id % 2}  #按模运算分配
          table-strategy:
            inline:
              sharding-column: sex
              algorithm-expression: t_user${sex % 2}  #按模运算分配